<?php use Illuminate\Database\Schema\Blueprint; use Illuminate\Database\Migrations\Migration; class TextRechnrMeasurement extends Migration {
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('text_rechnr_measurement',function($table){
			$table->increments('domain_id');
			$table->string('calculator_name',25)->nullable();
			$table->string('metric',15)->nullable();
			$table->string('weight',15)->nullable();
				$table->string('mg',30)->nullable();
				$table->string('ounce',30)->nullable();
				$table->string('gram',30)->nullable();
				$table->string('decagram',30)->nullable();
				$table->string('pound',30)->nullable();
				$table->string('kilogram',30)->nullable();
				$table->string('short_ton',30)->nullable();
				$table->string('metric_ton',30)->nullable();
				$table->string('carat',30)->nullable();
			$table->string('length',15)->nullable();
				$table->string('mm',30)->nullable();
				$table->string('cm',30)->nullable();
				$table->string('dm',30)->nullable();
				$table->string('m',30)->nullable();
				$table->string('km',30)->nullable();
				$table->string('inch',30)->nullable();
				$table->string('foot',30)->nullable();
				$table->string('yard',30)->nullable();
				$table->string('fathom',30)->nullable();
				$table->string('link',30)->nullable();
				$table->string('rod',30)->nullable();
				$table->string('chain',30)->nullable();
				$table->string('statute_miles',30)->nullable();
				$table->string('nautical_miles',15)->nullable();
			$table->string('speed',30)->nullable();
				$table->string('kmph',30)->nullable();
				$table->string('mps',30)->nullable();
				$table->string('ftph',30)->nullable();
				$table->string('mph',30)->nullable();
				$table->string('knots',30)->nullable();
				$table->string('mach',30)->nullable();
			$table->string('area',30)->nullable();
				$table->string('mm2',30)->nullable();
				$table->string('cm2',30)->nullable();
				$table->string('dm2',30)->nullable();
				$table->string('m2',30)->nullable();
				$table->string('square_inch',30)->nullable();
				$table->string('square_foot',30)->nullable();
				$table->string('are',30)->nullable();
				$table->string('acre',30)->nullable();
				$table->string('hectare',30)->nullable();
			$table->string('temperature',30)->nullable();
				$table->string('celcius',30)->nullable();
				$table->string('fahrenheit',30)->nullable();
				$table->string('kelvin',30)->nullable();
			$table->string('data',30)->nullable();
				$table->string('bit',30)->nullable();
				$table->string('byte',30)->nullable();
				$table->string('kilobyte',30)->nullable();
				$table->string('megabyte',30)->nullable();
				$table->string('gigabyte',30)->nullable();
				$table->string('terabyte',30)->nullable();
				$table->string('petabyte',30)->nullable();
				$table->string('exabyte',30)->nullable();
				$table->string('zettabyte',30)->nullable();
				$table->string('yottabyte',30)->nullable();
			$table->string('perf',30)->nullable();
				$table->string('kW',30)->nullable();
				$table->string('PS',30)->nullable();
			$table->string('vol',30)->nullable();
				$table->string('ml',30)->nullable();
				$table->string('cl',30)->nullable();
				$table->string('dl',30)->nullable();
				$table->string('l',30)->nullable();
				$table->string('mm3',30)->nullable();
				$table->string('cm3',30)->nullable();
				$table->string('dm3',30)->nullable();
				$table->string('m3',30)->nullable();
				$table->string('cubic_inch',30)->nullable();
			$table->string('quant',30)->nullable();
				$table->string('brace',30)->nullable();
				$table->string('dozen',30)->nullable();
				$table->string('baker_dozen',30)->nullable();
				$table->string('score',30)->nullable();
				$table->string('gross',30)->nullable();
			$table->string('select',15)->nullable();
			$table->string('measure_from',15)->nullable();
			$table->string('measure_to',15)->nullable();
			$table->string('calculate',30)->nullable();
			$table->text('result')->nullable();
			$table->text('description_title')->nullable();
			$table->text('description_body')->nullable();
		});
	}
	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('text_rechnr_measurement');
	}
}
